right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
# uncomment the following to use ikfast kinematics plugin
# kinematics_solver: ik_fast_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 2

head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 2

